/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Arco;
import Clases.Vertice;
import EstructurasDeDatos.Grafo;
import javax.swing.JOptionPane;

/**
 *
 * @author fabriziospiotta
 */
public class InterfazAgregarAlmacen extends javax.swing.JFrame {

    static Grafo grafoWarehouse;
    /**
     * Creates new form InterfazAgregarAlmacen
     */
    public InterfazAgregarAlmacen(Grafo grafoWarehouse) {
        this.grafoWarehouse = grafoWarehouse;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaAlmacenNombre = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaNuevosArcos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AgregarAlmacenButton = new javax.swing.JButton();
        MenuButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        TextAreaAlmacenNombre.setColumns(20);
        TextAreaAlmacenNombre.setRows(5);
        jScrollPane1.setViewportView(TextAreaAlmacenNombre);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 100));

        TextAreaNuevosArcos.setColumns(20);
        TextAreaNuevosArcos.setRows(5);
        jScrollPane2.setViewportView(TextAreaNuevosArcos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 100));

        jLabel1.setText("Para ingresar un nuevo almacen, porfavor coloque el nombre que debe llevar el mismo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("en el recuadro de la izquierda (Debe ser una letra que no se encuentra en el grafo)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("y en el recuadro de la izquierda establezca dos nuevos arcos que involucren dicho almacen nuevo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setText("para que pueda ser creado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setText("INTRODUZCA NOMBRE DEL ALMACEN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setText("Coloque solo la letra (Mayuscula) ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel7.setText("INTRODUZCA LOS DOS ARCOS NUEVOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel8.setText("Estructura para aceptar los nuevos arcos en el programa --> ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 20));

        jLabel9.setText("NombreAlmacenOrigen, NombreAlmacenDestino, distancia \\n");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, 20));

        AgregarAlmacenButton.setText("AGREGAR ALMACEN");
        AgregarAlmacenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAlmacenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarAlmacenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        MenuButton.setText("VOLVER AL MENU");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        jLabel10.setText("Las letras en mayusculas preferiblemente");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarAlmacenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAlmacenButtonActionPerformed
        // TODO add your handling code here:
        try {
            int cont = 0;
            if ("".equals(TextAreaAlmacenNombre.getText()) || "".equals(TextAreaNuevosArcos.getText())) {
                JOptionPane.showMessageDialog(null, "ERROR! Ambos campos deben estar llenos");
            }
            else {
                String nombreNewVertice = TextAreaAlmacenNombre.getText();
                char nombreChar = nombreNewVertice.charAt(0);
                int numberNewVertice = nombreChar - 65;
                Vertice newVertice = new Vertice(nombreNewVertice, numberNewVertice);
                if (grafoWarehouse.encontrarAlmacen(newVertice) == true) {
                    JOptionPane.showMessageDialog(null, "ERROR! Ese almacen ya existe");
                } else {
                    String [] arrayArcos = TextAreaNuevosArcos.getText().split("\n");
                    for (int i = 0; i < arrayArcos.length; i++) {
                        String [] miniArray = arrayArcos[i].split(",");
                        Arco newArco = new Arco(miniArray[0], miniArray[1], Integer.parseInt(miniArray[2]));
                        if (newArco.getVerticeOrigenNombre().equalsIgnoreCase(nombreNewVertice)) {
                            newVertice.getListaDeAdyacencia().AppendAtTheEnd(newArco);
                            cont += 1;
                        } 
                        else if (newArco.getVerticeDestinoNombre().equalsIgnoreCase(nombreNewVertice)) {
                            grafoWarehouse.insertarArco(newArco);
                            cont += 1;
                        }
                    }
                }

                if (cont >= 2) {
                    grafoWarehouse.insertarVertice(newVertice);
                    JOptionPane.showMessageDialog(null, "Almacen agregado con Exito!");
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR! Debe ingresar dos arcos nuevos relacionados con el nuevo almacen que esta agregando");
                }
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DESCONOCIDO! . \nTipo de error: " + e);
        }
        
    }//GEN-LAST:event_AgregarAlmacenButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        InterfazMenu menu = new InterfazMenu(grafoWarehouse);
        menu.setVisible(true);
    }//GEN-LAST:event_MenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAgregarAlmacen(grafoWarehouse).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAlmacenButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JTextArea TextAreaAlmacenNombre;
    private javax.swing.JTextArea TextAreaNuevosArcos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
